# Generated by Django 5.0.3 on 2024-06-07 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_parent_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='GazeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Timestamp', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('state', models.CharField(max_length=255)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.player')),
            ],
        ),
    ]
