# Generated by Django 5.0.3 on 2024-06-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyeTracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gazedata',
            old_name='Timestamp',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='gazedata',
            name='state',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gazedata',
            name='x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gazedata',
            name='y',
            field=models.FloatField(),
        ),
    ]
