# Generated by Django 5.0.3 on 2024-06-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyeTracking', '0002_rename_timestamp_gazedata_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gazedata',
            name='x',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gazedata',
            name='y',
            field=models.IntegerField(),
        ),
    ]
