# Generated by Django 5.0.3 on 2024-06-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyeTracking', '0003_alter_gazedata_x_alter_gazedata_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gazedata',
            name='state',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gazedata',
            name='timestamp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gazedata',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gazedata',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
