# Generated by Django 5.0.3 on 2024-06-07 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eyeTracking', '0004_alter_gazedata_state_alter_gazedata_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gazedata',
            name='player',
        ),
    ]
