# Generated by Django 5.0.3 on 2024-06-19 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eyeTracking', '0005_remove_gazedata_player'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GazeData',
        ),
    ]
