# Generated by Django 5.0.3 on 2024-06-19 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eyeTracking', '0009_gazedata_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gazedata',
            old_name='sacacdes_to_fixations',
            new_name='saccades_to_fixations',
        ),
    ]
