# Generated by Django 5.0.3 on 2024-06-20 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eyeTracking', '0010_rename_sacacdes_to_fixations_gazedata_saccades_to_fixations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gazedata',
            old_name='saccades_to_fixations',
            new_name='sacades_to_fixations',
        ),
    ]
