# Generated by Django 5.0.6 on 2024-06-23 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyeTracking', '0012_rename_sacades_to_fixations_gazedata_saccades_to_fixations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gazedata',
            name='player',
        ),
        migrations.AddField(
            model_name='gazedata',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
