# Generated by Django 5.0.6 on 2024-06-23 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_parent_teacher'),
        ('eyeTracking', '0013_remove_gazedata_player_gazedata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gazedata',
            name='user',
        ),
        migrations.AddField(
            model_name='gazedata',
            name='player',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.player'),
        ),
    ]
