# Generated by Django 5.0.6 on 2024-06-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='backgroundColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='white', max_length=256)),
                ('AFD', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='charSpacing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(default=1.0)),
                ('AFD', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='fontType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Arial', max_length=256)),
                ('AFD', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='textColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='black', max_length=256)),
                ('AFD', models.FloatField(default=0.0)),
            ],
        ),
    ]
