# Generated by Django 5.0.6 on 2024-06-20 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation', '0001_initial'),
        ('authentication', '0002_parent_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundcolor',
            name='player',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.player'),
        ),
        migrations.AddField(
            model_name='charspacing',
            name='player',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.player'),
        ),
        migrations.AddField(
            model_name='fonttype',
            name='player',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.player'),
        ),
        migrations.AddField(
            model_name='textcolor',
            name='player',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.player'),
        ),
    ]
