# Generated by Django 5.0.3 on 2024-06-20 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation', '0002_backgroundcolor_player_charspacing_player_and_more'),
        ('authentication', '0002_parent_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charspacing',
            name='player',
        ),
        migrations.RemoveField(
            model_name='fonttype',
            name='player',
        ),
        migrations.RemoveField(
            model_name='textcolor',
            name='player',
        ),
        migrations.CreateModel(
            name='browserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting', models.CharField(default='', max_length=256)),
                ('player', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.player')),
            ],
        ),
        migrations.DeleteModel(
            name='backgroundColor',
        ),
        migrations.DeleteModel(
            name='charSpacing',
        ),
        migrations.DeleteModel(
            name='fontType',
        ),
        migrations.DeleteModel(
            name='textColor',
        ),
    ]
