# Generated by Django 5.0.3 on 2024-06-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation', '0003_remove_charspacing_player_remove_fonttype_player_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='browsersettings',
            old_name='setting',
            new_name='charSpacing',
        ),
        migrations.AddField(
            model_name='browsersettings',
            name='bgColor',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='browsersettings',
            name='fontColor',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='browsersettings',
            name='fontType',
            field=models.CharField(default='', max_length=256),
        ),
    ]
