# Generated by Django 5.0.3 on 2024-06-20 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation', '0005_adaptation_gazedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adaptation_gazedata',
            name='avg_saccade_duration',
        ),
        migrations.RemoveField(
            model_name='adaptation_gazedata',
            name='saccades_to_fixations',
        ),
        migrations.RemoveField(
            model_name='adaptation_gazedata',
            name='total_fixations',
        ),
        migrations.RemoveField(
            model_name='adaptation_gazedata',
            name='total_saccades',
        ),
    ]
