# Generated by Django 5.0.3 on 2024-06-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation', '0006_remove_adaptation_gazedata_avg_saccade_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaptation_gazedata',
            name='extention_no',
            field=models.IntegerField(default=0),
        ),
    ]
