# Generated by Django 5.0.6 on 2024-06-20 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation', '0007_adaptation_gazedata_extention_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adaptation_gazedata',
            name='avg_fix_duration',
        ),
        migrations.RemoveField(
            model_name='adaptation_gazedata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='adaptation_gazedata',
            name='extention_no',
        ),
        migrations.RemoveField(
            model_name='adaptation_gazedata',
            name='player',
        ),
        migrations.AddField(
            model_name='adaptation_gazedata',
            name='base_afd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adaptation_gazedata',
            name='min_bg_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adaptation_gazedata',
            name='min_bg_color_afd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adaptation_gazedata',
            name='min_char_spacing',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adaptation_gazedata',
            name='min_char_spacing_afd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adaptation_gazedata',
            name='min_font_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adaptation_gazedata',
            name='min_font_color_afd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adaptation_gazedata',
            name='min_font_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adaptation_gazedata',
            name='min_font_type_afd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adaptation_gazedata',
            name='overall_gain',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adaptation_gazedata',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='browserSettings',
        ),
    ]
